=== AlekseyBykov/pets.xsd/src/test/resources/schema/complextype/book/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="../person/person.xsd"/>
    <xsd:include schemaLocation="../uint/uint.xsd"/>

    <xsd:complexType name="Book">
        <xsd:sequence>
            <xsd:element name="isbn" type="xsd:string"/>
            <xsd:element name="title" type="xsd:token"/>
            <xsd:element name="person" type="Person"/>
            <xsd:element name="publisher" type="xsd:token" maxOccurs="unbounded"/>
            <xsd:element name="page_number" type="UnsignedInt"/>
            <xsd:element name="description" type="xsd:string" minOccurs="0"/>
            <xsd:choice>
                <xsd:element name="papper"/>
                <xsd:element name="other"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="book" type="Book"/>

</xsd:schema>

=== AlekseyBykov/pets.xsd/src/test/resources/schema/complextype/book/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="book.xsd">

    <isbn>9781846282522</isbn>
    <title>Fundamental Networking in Java</title>
    <person>
        <first_name>Pitt</first_name>
        <last_name>Esmond</last_name>
    </person>
    <publisher>Apress</publisher>
    <page_number>382</page_number>
    <description>The book provides complete coverage of fundamental IP networking in Java</description>
    <papper/>

</book>
