=== AlekseyBykov/pets.xsd/src/test/resources/schema/complextype/nested.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name = "UnsignedInt">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="0"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="Book">
        <xsd:sequence>
            <xsd:element name="isbn" type="xsd:string"/>
            <xsd:element name="title" type="xsd:token"/>
            <xsd:element name="author" type="xsd:token"/>
            <xsd:element name="publisher" type="xsd:token" maxOccurs="unbounded"/>
            <xsd:element name="page_number" type="UnsignedInt"/>
            <xsd:element name="description" type="xsd:string" minOccurs="0"/>
            <xsd:choice>
                <xsd:element name="papper"/>
                <xsd:element name="other"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Page">
        <xsd:all>
            <xsd:element name="book" type="Book"/>
            <xsd:element name="number" type="xsd:int"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:element name="book" type="Book"/>
    <xsd:element name="page" type="Page"/>

</xsd:schema>

=== AlekseyBykov/pets.xsd/src/test/resources/schema/complextype/nested_valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nested.xsd">
<isbn>string</isbn>
  <title>token</title>
  <author>token</author>
  <!--1 or more repetitions:-->
  <publisher>token</publisher>
  <page_number>3</page_number>
  <!--Optional:-->
  <description>string</description>
  <!--choise of the next 2 items at this level-->
  <papper>anyType</papper>
  <!--other>anyType</other-->
</book>
