=== AlekseyBykov/pets.xsd/src/test/resources/schema/complextype/letter/Letter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <xsd:group name="person">
        <xsd:sequence>
            <xsd:element name="firstName"/>
            <xsd:element name="lastName" minOccurs="0"/>
            <xsd:element name="middleName" minOccurs="0"/>
        </xsd:sequence>
    </xsd:group>
    
    <xsd:element name="letter">
        <xsd:complexType mixed="true">
            <xsd:sequence>
                <xsd:group ref="person"/>
                <xsd:element name="id" type="xsd:long"/>
                <xsd:sequence maxOccurs="unbounded">
                    <xsd:element name="title" type="xsd:token"/>
                    <xsd:element name="count" type="xsd:int"/>
                </xsd:sequence>
                <xsd:element name="total" type="xsd:double"/>
                <xsd:element name="currency" type="xsd:token"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== AlekseyBykov/pets.xsd/src/test/resources/schema/complextype/Letter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XSLT can be added here -->
<letter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="letter/Letter.xsd">Dear <firstName>Name</firstName>,
    Your order: <id>1</id>.
    <title>Order 1 name</title> - <count>10</count>
    <title>Order 2 name</title> - <count>20</count>
    <title>Order 3 name</title> - <count>30</count>
    Total coast: <total>100</total><currency>USD</currency>
</letter>
